apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa

spec:
  selector:
    matchLabels:
      name: go-hpa
  template:
    metadata:
      labels:
        name: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: app_go
          entrypoint: './hello'
          ports:
           - containerPort: 80
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"